name: "WordPress Plugin Build Zip"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build plugin
        run: npm install
        # Does not work until @goodwp/goodenberg is available
        # run: |
        #   npm install
        #   npm run build
      - name: Generate zip archive
        run: npm run plugin-zip
      - name: Upload the archive as an artifact
        id: upload-plugin-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: wc-vienna-2024.zip
